In [ ]:
#Predictors for our ML model
features = ['ROAD_TYPE', 'AGE_LESS_THAN_15YRS_PCNT', 'AGE_15_24YRS_PCNT', 'AGE_25_44YRS_PCNT', 'AGE_45_64YRS_PCNT', 'AGE_65YRS_OVER_PCNT', 'FC_COUPLE_NO_CHILDREN_PCNT', 'Intersection','traffic_signal','km_post','secondary_school','primary_school','Supermarket','Primary_Production%','Parkland%','Residential%','Industrial%','Commercial%','DWELLING_FLAT_UNIT_APART_PCNT','DWELLING_SEMID_RO_OR_TCE_H_TH_P','DWELLING_SEP_HOUSE_PCNT','FC_COUPLE_WITH_CHILDREN_PCNT', 'CARS_ONE_HH_PCNT', 'CARS_TWO_OR_MORE_HH_PCNT' ]

X = X=records[features]

#and our label attribute
y=records['BLACKSPOTS']

In [ ]:
# checking how many rows and columns are there
X.shape

(5326, 24)

In [ ]:
y.shape

(5326,)

<a id = "cell_modeling"></a>
## 3. Machine learning model development


This section includes:
* How to split dataset.
* How to initiate machine learning model and fit training data.
* How to use trained model to predict labels for training and testing dataset.

In [ ]:
# Code
from sklearn.model_selection import train_test_split

In [ ]:
# now we are splitting out dataset for testing and training, we are using 80% for testing and 20% for training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
#looking whether the splitted dataset are right or not
print(X_train.info())
print(X_test.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4260 entries, 593 to 5157
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ROAD_TYPE                        4260 non-null   int64
 1   AGE_LESS_THAN_15YRS_PCNT         4260 non-null   float64
 2   AGE_15_24YRS_PCNT                4260 non-null   float64
 3   AGE_25_44YRS_PCNT                4260 non-null   float64
 4   AGE_45_64YRS_PCNT                4260 non-null   float64
 5   AGE_65YRS_OVER_PCNT              4260 non-null   float64
 6   FC_COUPLE_NO_CHILDREN_PCNT       4260 non-null   float64
 7   Intersection                     4260 non-null   int64
 8   traffic_signal                   4260 non-null   int64
 9   km_post                          4260 non-null   int64
 10  secondary_school                 4260 non-null   int64
 11  primary_school                   4260 non-null   int64
 12  Supermarket                      4260 non-null   int64
 13  Primary_Production%              4260 non-null   float64
 14  Parkland%                        4260 non-null   float64
 15  Residential%                     4260 non-null   float64
 16  Industrial%                      4260 non-null   float64
 17  Commercial%                      4260 non-null   float64
 18  DWELLING_FLAT_UNIT_APART_PCNT    4260 non-null   float64
 19  DWELLING_SEMID_RO_OR_TCE_H_TH_P  4260 non-null   float64
 20  DWELLING_SEP_HOUSE_PCNT          4260 non-null   float64
 21  FC_COUPLE_WITH_CHILDREN_PCNT     4260 non-null   float64
 22  CARS_ONE_HH_PCNT                 4260 non-null   float64
 23  CARS_TWO_OR_MORE_HH_PCNT         4260 non-null   float64
dtypes: float64(17), int64(7)
memory usage: 832.0 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1066 entries, 4817 to 2027
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ROAD_TYPE                        1066 non-null   int64
 1   AGE_LESS_THAN_15YRS_PCNT         1066 non-null   float64
 2   AGE_15_24YRS_PCNT                1066 non-null   float64
 3   AGE_25_44YRS_PCNT                1066 non-null   float64
 4   AGE_45_64YRS_PCNT                1066 non-null   float64
 5   AGE_65YRS_OVER_PCNT              1066 non-null   float64
 6   FC_COUPLE_NO_CHILDREN_PCNT       1066 non-null   float64
 7   Intersection                     1066 non-null   int64
 8   traffic_signal                   1066 non-null   int64
 9   km_post                          1066 non-null   int64
 10  secondary_school                 1066 non-null   int64
 11  primary_school                   1066 non-null   int64
 12  Supermarket                      1066 non-null   int64
 13  Primary_Production%              1066 non-null   float64
 14  Parkland%                        1066 non-null   float64
 15  Residential%                     1066 non-null   float64
 16  Industrial%                      1066 non-null   float64
 17  Commercial%                      1066 non-null   float64
 18  DWELLING_FLAT_UNIT_APART_PCNT    1066 non-null   float64
 19  DWELLING_SEMID_RO_OR_TCE_H_TH_P  1066 non-null   float64
 20  DWELLING_SEP_HOUSE_PCNT          1066 non-null   float64
 21  FC_COUPLE_WITH_CHILDREN_PCNT     1066 non-null   float64
 22  CARS_ONE_HH_PCNT                 1066 non-null   float64
 23  CARS_TWO_OR_MORE_HH_PCNT         1066 non-null   float64
dtypes: float64(17), int64(7)
memory usage: 208.2 KB
None

In [ ]:
#creation of logistic regression model as it is the problem of classification
logreg = LogisticRegression(max_iter=100)
logreg

LogisticRegression()

In [ ]:
#training the model
logreg = logreg.fit(X_train, y_train)

In [ ]:
#making predictions using the model
y_pred = logreg.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
#looking wheter the predicted values are similar to or not the actual values
y_test.values.T

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
#here we are creating a table of camparision whether the prdeicted and actul values corelate or not
inspection=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

inspection=pd.concat([X_test,inspection], axis=1)
#looking at initial 15 entries
inspection.head(15)

,ROAD_TYPE,AGE_LESS_THAN_15YRS_PCNT,AGE_15_24YRS_PCNT,AGE_25_44YRS_PCNT,AGE_45_64YRS_PCNT,AGE_65YRS_OVER_PCNT,FC_COUPLE_NO_CHILDREN_PCNT,Intersection,traffic_signal,km_post,...,Industrial%,Commercial%,DWELLING_FLAT_UNIT_APART_PCNT,DWELLING_SEMID_RO_OR_TCE_H_TH_P,DWELLING_SEP_HOUSE_PCNT,FC_COUPLE_WITH_CHILDREN_PCNT,CARS_ONE_HH_PCNT,CARS_TWO_OR_MORE_HH_PCNT,Actual,Predicted
4817,0,0.271825,0.083333,0.236111,0.271825,0.136905,0.391304,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.485507,0.322981,0.652174,1,1
1039,3,0.163090,0.124464,0.180258,0.360515,0.171674,0.428571,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.571429,0.162162,0.797297,1,1
4700,3,0.141921,0.124454,0.148472,0.351528,0.233624,0.488189,1,0,0,...,0.0,0.000000,0.000000,0.025157,0.955975,0.377953,0.248408,0.732484,1,1
3194,3,0.185304,0.102236,0.194888,0.348243,0.169329,0.505155,1,0,1,...,0.0,0.000000,0.000000,0.000000,1.000000,0.360825,0.177570,0.785047,1,1
440,4,0.218519,0.133333,0.224074,0.259259,0.164815,0.321429,0,0,0,...,0.0,0.000000,0.014778,0.039409,0.945813,0.464286,0.405128,0.564103,1,1
1034,3,0.144847,0.130919,0.208914,0.348189,0.167131,0.456522,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.423913,0.121739,0.852174,1,1
4166,3,0.206522,0.101449,0.188406,0.344203,0.159420,0.387283,1,0,0,...,0.0,0.000000,0.000000,0.000000,0.984375,0.514451,0.128866,0.850515,1,1
3546,3,0.126521,0.102190,0.182482,0.350365,0.238443,0.500000,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.325000,0.278481,0.683544,1,1
4365,4,0.121988,0.058735,0.228916,0.269578,0.320783,0.575758,0,0,1,...,0.0,0.177746,0.122727,0.059091,0.745455,0.303030,0.429224,0.461187,1,0
1774,3,0.218054,0.080891,0.256741,0.237984,0.206331,0.466667,1,0,0,...,0.0,0.000000,0.000000,0.025157,0.959119,0.333333,0.387500,0.537500,1,1
2847,3,0.204509,0.098229,0.198068,0.336554,0.162641,0.441860,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.406977,0.188841,0.742489,1,1
4926,2,0.268759,0.070941,0.312415,0.263302,0.084584,0.380488,1,0,1,...,0.0,0.000000,0.000000,0.000000,1.000000,0.590244,0.133603,0.834008,1,1
5160,4,0.087264,0.070755,0.117925,0.271226,0.452830,0.589474,0,0,1,...,0.0,0.000000,0.000000,0.000000,1.000000,0.252632,0.547368,0.331579,0,1
988,4,0.203175,0.112698,0.196825,0.307937,0.179365,0.416667,1,0,0,...,0.0,0.000000,0.000000,0.025316,0.928270,0.403846,0.338912,0.552301,1,1
2488,3,0.121495,0.130841,0.233645,0.392523,0.121495,0.285714,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.785714,0.142857,0.857143,1,1

In [ ]:
#looking at last entries (15)
inspection.tail(15)

,ROAD_TYPE,AGE_LESS_THAN_15YRS_PCNT,AGE_15_24YRS_PCNT,AGE_25_44YRS_PCNT,AGE_45_64YRS_PCNT,AGE_65YRS_OVER_PCNT,FC_COUPLE_NO_CHILDREN_PCNT,Intersection,traffic_signal,km_post,...,Industrial%,Commercial%,DWELLING_FLAT_UNIT_APART_PCNT,DWELLING_SEMID_RO_OR_TCE_H_TH_P,DWELLING_SEP_HOUSE_PCNT,FC_COUPLE_WITH_CHILDREN_PCNT,CARS_ONE_HH_PCNT,CARS_TWO_OR_MORE_HH_PCNT,Actual,Predicted
1081,3,0.212308,0.104615,0.187692,0.378462,0.116923,0.494949,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.494949,0.120690,0.853448,1,1
1852,3,0.234450,0.124402,0.236045,0.261563,0.143541,0.333333,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.488506,0.185366,0.765854,1,1
4716,0,0.131532,0.079279,0.153153,0.291892,0.344144,0.521739,1,0,0,...,0.0,0.010868,0.098485,0.034091,0.829545,0.246377,0.425455,0.370909,1,1
1587,0,0.131532,0.079279,0.153153,0.291892,0.344144,0.521739,1,0,1,...,0.0,0.198706,0.098485,0.034091,0.829545,0.246377,0.425455,0.370909,1,1
3301,4,0.248780,0.126829,0.239024,0.273171,0.112195,0.289720,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.570093,0.201493,0.708955,1,1
622,3,0.144578,0.072289,0.162651,0.403614,0.216867,0.500000,1,0,0,...,0.0,0.000000,0.000000,0.000000,0.968992,0.371795,0.214815,0.696296,1,1
1953,0,0.166990,0.091262,0.217476,0.304854,0.219417,0.405797,1,0,0,...,0.0,0.000000,0.032258,0.000000,0.967742,0.369565,0.412556,0.479821,0,1
3900,3,0.185366,0.126829,0.187805,0.343902,0.156098,0.483333,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.408333,0.195804,0.804196,1,1
2595,3,0.248780,0.126829,0.239024,0.273171,0.112195,0.289720,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.570093,0.201493,0.708955,1,1
804,0,0.176378,0.140157,0.171654,0.277165,0.234646,0.352941,1,0,0,...,0.0,0.000000,0.000000,0.012000,0.976000,0.405229,0.412955,0.425101,0,1
1030,3,0.182573,0.062241,0.153527,0.398340,0.203320,0.458333,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.333333,0.220000,0.700000,1,1
587,3,0.211268,0.123239,0.207746,0.330986,0.126761,0.448276,1,0,0,...,0.0,0.000000,0.000000,0.000000,0.961165,0.471264,0.125000,0.875000,1,1
3344,3,0.163090,0.124464,0.180258,0.360515,0.171674,0.428571,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.571429,0.162162,0.797297,1,1
4721,3,0.201087,0.116848,0.198370,0.369565,0.114130,0.372549,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.539216,0.160000,0.808000,1,1
2027,3,0.177419,0.150538,0.153226,0.336022,0.182796,0.378641,1,0,0,...,0.0,0.000000,0.000000,0.000000,1.000000,0.495146,0.139130,0.826087,1,1